name: Terraform CI Action Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7  # My Terraform version on local machine

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform Code
        run: terraform fmt -recursive

      - name: Validate Terraform Configuration
        run: terraform validate