name: Terraform CI Action Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform CI Validation  # This should show up in the Actions tab

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7  # Your Terraform version on local machine

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform Code
        run: terraform fmt -recursive

      - name: Validate Terraform Configuration
        run: terraform validate
